### ISSUE TITLE
setup time too long

### ISSUE THREAD

**Issue by ghost** [hzi-braunschweig/pia-system#1]
setting up the docker system as described in the readme, the building process of the webappserver seems to have an infinite loop or whatever. See the snipplet from the log:

```
...
 => => naming to registry.netzlink.com/pia/psa.app.mobile:latest                                                                                         0.0s
Successfully built 7a8617345589f2b02e1b598ef92f82d7a9e1eec6dd6d5833741a635b50f96e7c                                                                           
Building webappserver
[+] Building 1971.1s (12/21)                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                     0.0s 
...
```
What is so timeconsuming building a webapp server?

# reproduce
on a debian bullseye linux, do as described in the readme:
* clone the repository
* cd pia-ansible/local
* ./start.sh

**Comment by ghost** [comment]
meanwhile, I've given up after
```
[+] Building 18187.6s (12/21)
```
Please create a usable docker version or provide a ready to go docker container.

**Comment by ghdoergeloh** [comment]
Currently we cannot see the problem here. I just tried it in an unchanged repo clone.

We just saw that you use bullseye (which is testing) so we haven't tested it on that distribution.

- Maybe it is your dockerversion (I am using Docker version 20.10.7 and docker-compose version 1.28.6).
- Maybe it is your internetconnection?
- If it hangs up on "load build definition from Dockerfile" maybe there are some permission errors?

**Comment by ghost** [comment]
> Currently we cannot see the problem here. I just tried it in an unchanged repo clone.
> 
> We just saw that you use bullseye (which is testing) so we haven't tested it on that distribution.

yes, this might be an issue. But bullseye is up to become the next stable, assumed to be in one or two months - better to be prepared for that, or do you only support oldstable then?

However, there is no restriction in the Prerequisites of your project readme, maybe you could be more specific in the requirements?

>     * Maybe it is your dockerversion (I am using Docker version 20.10.7 and docker-compose version 1.28.6).

Here, I've installed docker version 5:20.10.7\~3\~0~debian-buster and docker-compose 1.25.0-1 (from bullseye repo)

>     * Maybe it is your internetconnection?

Could be an issue, but there was no network traffic in that time. But for such an application, why would the internet connection speed be such a limitation? It's only an ecrf what you provide, there shouldn't be such an overhead for a simple installation (yet it becomes big enough through docker).

>     * If it hangs up on "load build definition from Dockerfile" maybe there are some permission errors?

Again, I only wanted to start the application as described in your readme. If I have permission errors, then they must be within of your docker container. I didn't change anything.

**Comment by ghdoergeloh** [comment]
I tried it in a bullseye vm. I got

```
Building mobileappasset
[+] Building 4.4s (13/15)                                                                                                                                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                 0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                    0.0s
 => => transferring context: 35B                                                                                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/busybox:1.33.1@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:14.17.0-alpine@sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c                                                                                                                                       1.8s
 => [build-browser 1/8] FROM docker.io/library/node:14.17.0-alpine@sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c                                                                                                                                           0.0s
 => [internal] load build context                                                                                                                                                                                                                                                    0.3s
 => => transferring context: 25.39kB                                                                                                                                                                                                                                                 0.3s
 => CACHED [stage-1 1/2] FROM docker.io/library/busybox:1.33.1@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d                                                                                                                                               0.0s
 => CACHED [build-browser 2/8] RUN npm install -g cordova                                                                                                                                                                                                                            0.0s
 => CACHED [build-browser 3/8] RUN npm install -g @ionic/cli                                                                                                                                                                                                                         0.0s
 => CACHED [build-browser 4/8] WORKDIR /app                                                                                                                                                                                                                                          0.0s
 => CACHED [build-browser 5/8] COPY psa.app.mobile/package*.json ./                                                                                                                                                                                                                  0.0s
 => CACHED [build-browser 6/8] RUN npm ci                                                                                                                                                                                                                                            0.0s
 => CACHED [build-browser 7/8] COPY psa.app.mobile/ .                                                                                                                                                                                                                                0.0s
 => [build-browser 8/8] RUN npm run build:browser                                                                                                                                                                                                                                    2.1s
cannot write /tmp/tmp2rn54rul because server did not provide an image ID
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 350, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1108, in build
    all_events = list(stream_output(build_output, output_stream))
  File "/usr/lib/python3/dist-packages/compose/progress_stream.py", line 25, in stream_output
    for event in utils.json_stream(output):
  File "/usr/lib/python3/dist-packages/compose/utils.py", line 61, in split_buffer
    for data in stream_as_text(stream):
  File "/usr/lib/python3/dist-packages/compose/utils.py", line 37, in stream_as_text
    for data in stream:
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1816, in build
    with open(iidfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp2rn54rul'
```

when it tries to build the mobileappasset.
There it is connected to the docker-compose. The version 1.25.0 is old.
All other things seemed to work.

Can you install the latest version of docker and docker-compose as described in the official docker documentation?

**Comment by ghost** [comment]
using docker-compose 1.29.2, the build process works. Thank you for your support.

Obviously, the PIA system is not runnable with out of the box docker software from the native debian repository. Even sid uses the verison 1.25.0 (https://packages.debian.org/de/sid/docker-compose), and other projects using docker can handle this. You should consider to make the build process compatible with current stable debian packages.
